# Generated by Django 4.1.2 on 2022-10-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام ایستگاه')),
            ],
            options={
                'verbose_name': 'ایستگاه',
                'verbose_name_plural': 'ایستگاه ها',
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='مقدار بارش (به میلی متر )')),
                ('submit_date', models.DateField(verbose_name='تاریخ')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.station', verbose_name='نام ایستگاه')),
            ],
            options={
                'verbose_name': 'بارندگی',
                'verbose_name_plural': 'بارندگی ها',
            },
        ),
    ]
